/*
 * @author Tanner Leach
 * @date May 16, 2015
 * 
 * projectEuler.net Problem 12.
 * The sequence of triangle numbers is generated by 
 * adding the natural numbers. So the 7th triangle 
 * number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
 * The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55
 */

import java.io.*;

public class TriNumber{

    public static void main(String[] args){
        TriNumber tn = new TriNumber();
        tn.go();
    }

    public void go(){
        int tri = 0;
        int num = 0;
        int numDivisors = 0;

        do{
            //increment number to add
            num++;
            //get the next triangle number
            tri += num;

            numDivisors = this.getNumDivisors(tri);

        }while(numDivisors <= 500);

        System.out.println("Answer: " + tri);
    }

    public int getNumDivisors(int num){
        //Take sqr root
        int limit = (int)Math.sqrt(num) + 1;
        int counter = 0;

        for(int i = 1; i < limit; i++){
            if(num%i == 0)
                counter++;
        }
        //counte only has one half of the pairs
        //so multiply by 2 to get other in pair
        return counter*2;
    }
}
